// Generates src/favicon.ts (base64 ICO with 32px + 16px PNG frames).
// Pure Node — no dependencies.
//
// Design: dark rounded square (#111) with `{}` braces in the site accent
// (#4cc2ff) — JSON braces as the "example API" motif. Minimal, no gradients.
//
// Usage: node scripts/gen-favicon.mjs
// Also writes /tmp/favicon-32.png and /tmp/favicon-16.png for visual checks.

import { deflateSync } from 'node:zlib'
import { writeFileSync } from 'node:fs'

// --- PNG encoding (RGBA, 8-bit) -------------------------------------------

const CRC_TABLE = (() => {
  const t = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    t[n] = c >>> 0
  }
  return t
})()

function crc32(buf) {
  let c = 0xffffffff
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

function chunk(type, data) {
  const out = Buffer.alloc(8 + data.length + 4)
  out.writeUInt32BE(data.length, 0)
  out.write(type, 4, 'ascii')
  data.copy(out, 8)
  const crc = crc32(Buffer.concat([Buffer.from(type, 'ascii'), data]))
  out.writeUInt32BE(crc, 8 + data.length)
  return out
}

function encodePng(width, height, rgba) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 6 // color type RGBA
  const stride = 1 + width * 4
  const raw = Buffer.alloc(height * stride)
  for (let y = 0; y < height; y++) {
    raw[y * stride] = 0 // filter: none
    rgba.copy(raw, y * stride + 1, y * width * 4, (y + 1) * width * 4)
  }
  return Buffer.concat([sig, chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0))])
}

// --- Drawing ---------------------------------------------------------------

const BG = [0x11, 0x11, 0x11, 0xff] // #111
const FG = [0x4c, 0xc2, 0xff, 0xff] // #4cc2ff (site dark-mode accent)

function insideRounded(x, y, size, r) {
  const dx = Math.min(x, size - 1 - x)
  const dy = Math.min(y, size - 1 - y)
  if (dx >= r || dy >= r) return true
  return (r - dx) ** 2 + (r - dy) ** 2 <= r * r
}

function rect(img, size, x0, y0, x1, y1) {
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) {
      if (x >= 0 && y >= 0 && x < size && y < size) img[y * size + x] = FG
    }
  }
}

function draw(img, size, r) {
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      if (insideRounded(x, y, size, r)) img[y * size + x] = BG
    }
  }
  if (size === 32) {
    // { : wide top/bottom hooks overlapping the vertical bar
    rect(img, size, 5, 6, 12, 8)
    rect(img, size, 5, 8, 7, 23)
    rect(img, size, 5, 23, 12, 25)
    // } : mirrored
    rect(img, size, 19, 6, 26, 8)
    rect(img, size, 24, 8, 26, 23)
    rect(img, size, 19, 23, 26, 25)
  } else {
    // 16px
    rect(img, size, 2, 3, 6, 4)
    rect(img, size, 2, 4, 3, 11)
    rect(img, size, 2, 11, 6, 12)
    rect(img, size, 9, 3, 13, 4)
    rect(img, size, 12, 4, 13, 11)
    rect(img, size, 9, 11, 13, 12)
  }
}

function render(size, r) {
  const img = new Array(size * size).fill(null)
  draw(img, size, r)
  const rgba = Buffer.alloc(size * size * 4)
  for (let i = 0; i < img.length; i++) {
    const px = img[i]
    rgba.set(px ?? [0, 0, 0, 0], i * 4)
  }
  return { rgba, png: encodePng(size, size, rgba) }
}

// --- ICO container ----------------------------------------------------------

function encodeIco(frames) {
  const count = frames.length
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // type: icon
  header.writeUInt16LE(count, 4)

  const entries = []
  let offset = 6 + 16 * count
  for (const f of frames) {
    const e = Buffer.alloc(16)
    e[0] = f.size === 256 ? 0 : f.size
    e[1] = f.size === 256 ? 0 : f.size
    e[2] = 0 // colors
    e[3] = 0 // reserved
    e.writeUInt16LE(1, 4) // planes
    e.writeUInt16LE(32, 6) // bit count
    e.writeUInt32LE(f.png.length, 8)
    e.writeUInt32LE(offset, 12)
    offset += f.png.length
    entries.push(e)
  }
  return Buffer.concat([header, ...entries, ...frames.map((f) => f.png)])
}

// --- Main -------------------------------------------------------------------

const f32 = render(32, 7)
const f16 = render(16, 4)
const ico = encodeIco([
  { size: 32, png: f32.png },
  { size: 16, png: f16.png },
])

writeFileSync('/tmp/favicon-32.png', f32.png)
writeFileSync('/tmp/favicon-16.png', f16.png)

const b64 = ico.toString('base64')
writeFileSync(
  new URL('../src/favicon.ts', import.meta.url),
  `// Generated by scripts/gen-favicon.mjs — do not edit by hand.
// 32px + 16px ICO: dark rounded square with \`{}\` braces in the site accent.
export const FAVICON_ICO_BASE64 =
  '${b64}'

export function faviconIcoBytes(): Uint8Array<ArrayBuffer> {
  const bin = atob(FAVICON_ICO_BASE64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}
`,
)

// sanity checks
console.log('ico bytes:', ico.length, '| base64 chars:', b64.length)
console.log('ico magic:', ico.subarray(0, 4).toString('hex'), '(expect 00000100)')
console.log('entry count:', ico.readUInt16LE(4))
const px32 = f32.rgba
let fg = 0
for (let i = 0; i < px32.length; i += 4) if (px32[i + 3] === 255 && px32[i] === 0x4c) fg++
console.log('32px foreground pixels:', fg)
