// Generated by scripts/gen-favicon.mjs — do not edit by hand.
// 32px + 16px ICO: dark rounded square with `{}` braces in the site accent.
export const FAVICON_ICO_BASE64 =
  'AAABAAIAICAAAAEAIACqAAAAJgAAABAQAAABACAAfwAAANAAAACJUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIBgAAAHN6evQAAABxSURBVHic7dfBCQAhDARAW0hfV7WNeXBfdcHTbCKskKfuiA+TUsAys3aiUIZb6C+MdzhEsMKHCHZ4h0gHeGqDNTtwdd/09izAh0gP2H1nAQQQQAABBLgfEP4duwPCW7KUTSkdED6YpBjNWAgY7oVBGS/qeLq8BehDKwAAAABJRU5ErkJggolQTkcNChoKAAAADUlIRFIAAAAQAAAAEAgGAAAAH/P/YQAAAEZJREFUeJxjYEADgoKC//FhdPVEa8RrEKmaMQwBcXwO/cfAMIW45FBsJ8cAsCHoigg5e9QAehhAcjRSnJCokpQpzkyUZGcAmhGCUC0il2gAAAAASUVORK5CYII='

export function faviconIcoBytes(): Uint8Array<ArrayBuffer> {
  const bin = atob(FAVICON_ICO_BASE64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}
